[package]
name = "zecpaperwallet"
version = "0.1.0"
authors = ["ZecWallet"]
edition = "2018"
    
[dependencies]
clap = "~2.33"
zecpaperlib = { path = "../lib" }
json = "0.11.14"    
qrcode = { version = "0.8", default-features = false }
lodepng = "*"
printpdf = "0.2.8"
image = "0.21.2"